version: '3'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:4.0.0
    container_name: dz-mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod
  redis:
    image: redis:4.0.5-alpine
    container_name: dz-redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
networks:
  redis-net:
volumes:
  mongodb:
  mongodb_config:
  redis-data: