version: '3'
services:
  mongodb:
    image: mongo:4.0.0
    container_name: dz-mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod
volumes:
  mongodb:
  mongodb_config: